// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Python.OilWell.Api.Data;

#nullable disable

namespace Python.OilWell.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250921124617_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");
#pragma warning restore 612, 618
        }
    }
}
